### ISSUE TITLE
Teleport to another world on another server with custom coordinates.

### ISSUE THREAD

**Issue by columb** [mbax/Portals#1]
Teleport from portal to custom world with custom coordinates. Or way to link portals.

**Comment by scrayos** [comment]
Problem should be the Thing, that the Server where the Portal is on, absolutely has no Permission on the other Server, to teleport the User to a custom location on this Server. So the "Portals-Plugins" on each Server have to communicate with themselves.

**Comment by krisdestruction** [comment]
You just send the coords to the other server?

**Comment by FunnyJ2** [comment]
No, you can't do that. Scrayos is right.
