### ISSUE TITLE
Add horizontal by Z Documentation

### ISSUE THREAD

**Issue by krisdestruction** [mbax/Portals#5]
How do you make a portal HorizontalByZ? You don't document it anywhere in your plugin or on devbukkit.

**Comment by mbax** [comment]
Right in the configuration?

**Comment by krisdestruction** [comment]
"Next, define its shape. The leftmost column is the lowest X or Z (depending on horizontalByX)"
So if I set it to false, it will be by Z instead of X? If so please indicate that. Otherwise, I might think it's horizontalByZ: true.

**Comment by krisdestruction** [comment]
I believe the answer is:
horizontalByX: true
and
horizontalByZ: true

Can the dev confirm?

**Comment by mbax** [comment]
Uh. Wat. You don't CHANGE the config keys. Set it to false if not true.

**Comment by krisdestruction** [comment]
Can you please specify this in the config for clarity? "Set it to false if not true."

**Comment by mbax** [comment]
that's uh.... how logic works

**Comment by krisdestruction** [comment]
Yes, I'm not new to java programming and boolean logic. But it's just easier to have it written down in the documentation for future builds :)

**Comment by krisdestruction** [comment]
Sorry this is what I meant you should add:
Set to true if horizontal by X
Set to false if horizontal by Z
