### ISSUE TITLE
Help Please...

### ISSUE THREAD

**Issue by Jdmnetwork** [mbax/Portals#6]
Hello,
I really don't understand how to use this plugin. Please help me.
Thank you!

**Comment by mbax** [comment]
Documented in the config, you are defining the coordinates of what you are considering to be the "portal," coordinates which upon detecting player presence will teleport them to another server

**Comment by Jdmnetwork** [comment]
Thank you very much!

**Comment by Jdmnetwork** [comment]
Great plugin.
