### ISSUE TITLE
Plugin use

### ISSUE THREAD

**Issue by selfservice0** [mbax/Portals#9]
The config might make sense you, but I think everyone else is having a bad time. A little help would be wonderful.

Some examples of which are confusing
1)
  shape: |
    XOOX
    OOOO
    OOOO
    XOOX

Shape? This doesn't make sense. Are we building a portal? Does X represent any type of building material? And O?

2)
  world: world
  x: 100 # Lowest X
  y: 70 # Lowest Y
  z: 100 # Lowest Z

So we are selecting the area around the portal? "Lowest X" Lowest X of what?

3) target: hub # Target server

Target? I believe we put the server name from out bungeecord config here?

**Comment by 812402** [comment]
I agree. This plugin doesn't make much sense. I don't feel like using stargate since the portals are ugly. Teleporter is just not an option for obvious reasons. I thought this would be good since the portals are custom shape, but I have no idea how this works! Please help!

**Comment by mbax** [comment]
1) Shape of the defined rectangular region. O is a location considered as part of the portal. Block type is irrelevant
2) Lowest coordinates of the shape.
3) Bungeecord server name, same as in the /server command.
